{
 "title": "Camera Telraam Mouans Sartoux",
 "time": { "from": "2020-06-14T01:07:39.916Z", "to": "2020-10-04T01:07:39.916Z" },
 "panels": [
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  measure_datetime + interval '2' HOUR AS \"time\",\n  bike,\n  car,\n  pedestrian,\n  lorry\nFROM telraam\nWHERE\n  $__timeFilter(\"measure_datetime\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of cars and lorries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measure_datetime + interval '2' HOUR AS \"time\",\n  car,lorry\nFROM telraam\nWHERE\n  $__timeFilter(\"measure_datetime\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of bikes and pedestrians",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measure_datetime + interval '2' HOUR AS \"time\",\n  bike,pedestrian\nFROM telraam\nWHERE\n  $__timeFilter(\"measure_datetime\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  measure_datetime + interval '2' HOUR AS \"time\",\n  (car_speed_00*5+car_speed_10*15+car_speed_20*25+car_speed_30*35+car_speed_40*45+car_speed_50*55+car_speed_60*65+car_speed_70*75)\n/(car_speed_00 +car_speed_10+car_speed_20+car_speed_30+car_speed_40+car_speed_50+car_speed_60+car_speed_70) as speed\nFROM telraam\nWHERE\n  $__timeFilter(\"measure_datetime\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Traffic flow par jour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(measure_datetime,1d),\n  sum(car) AS \"car\",\n  sum(bike) AS \"bike\",\n  sum(pedestrian) AS \"pedestrian\",\n  sum(lorry) AS \"lorry\"\nFROM telraam\nWHERE\n  measure_datetime > NOW() - INTERVAL '6 months'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}