{
 "title": "Luxembourg Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "var_road", "label": "Road", "query": "select  road from camera" },
   { "name": "var_direction", "label": "Direction", "query": "select  direction from camera" },
   {
    "name": "var_camera",
    "label": "Camera",
    "query": "select camera from  camera where road = '$var_road' and direction = '$var_direction'"
   }
  ]
 },
 "panels": [
  {
   "title": "Flow $var_road",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.measure_datetime AS \"time\",\n  t.camera AS metric,\n  t.vehicle_flow_rate\nFROM trafic_time as t, camera as c\nWHERE\n  t.camera = c.camera AND\n  $__timeFilter(\"measure_datetime\") AND\n  c.road = '$var_road' AND\n  c.direction = '$var_direction'\nORDER BY c.direction_distance"
    }
   ]
  },
  {
   "title": "Current Speed $var_camera",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"measure_datetime\" AS \"time\",\n  average_vehicle_speed\nFROM trafic_time\nWHERE\n  $__timeFilter(\"measure_datetime\") AND\n  camera = '$var_camera'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Traffic Concentration $var_camera",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"measure_datetime\" AS \"time\",\n  camera AS metric,\n  traffic_concentration\nFROM trafic_time\nWHERE\n  $__timeFilter(\"measure_datetime\") and camera = '$var_camera'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Vehicle Flow Rate $var_camera",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"measure_datetime\" AS \"time\",\n  camera AS metric,\n  vehicle_flow_rate\nFROM trafic_time\nWHERE\n  $__timeFilter(\"measure_datetime\") and camera = '$var_camera'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average  Vehicle Speed $var_camera",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"measure_datetime\" AS \"time\",\n  camera AS metric,\n  average_vehicle_speed\nFROM trafic_time\nWHERE\n  $__timeFilter(\"measure_datetime\") and camera = '$var_camera'\nORDER BY 1,2"
    }
   ]
  }
 ]
}